### ISSUE TITLE
Install error on Xampp server (windows 10)

### ISSUE THREAD

**Issue by fsuuaas** [pionl/laravel-chunk-upload-example#10]
Problem 1
    - Installation request for sebastian/environment 3.1.x-dev -> satisfiable by sebastian/environment[3.1.x-dev].
    - sebastian/environment 3.1.x-dev requires ext-posix * -> the requested PHP extension posix is missing from your system.
  Problem 2
    - Installation request for sebastian/environment dev-master -> satisfiable by sebastian/environment[dev-master].
    - sebastian/environment dev-master requires ext-posix * -> the requested PHP extension posix is missing from your system.
  Problem 3
    - sebastian/environment 3.1.x-dev requires ext-posix * -> the requested PHP extension posix is missing from your system.
    - phpunit/phpunit 6.5.x-dev requires sebastian/environment ^3.1 -> satisfiable by sebastian/environment[3.1.x-dev].
    - Installation request for phpunit/phpunit 6.5.x-dev -> satisfiable by phpunit/phpunit[6.5.x-dev].

  To enable extensions, verify that they are enabled in your .ini files:
    - F:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by pionl** [comment]
Hi, as the message states, you are missing `ext-posix` extension on your system (PHP extension).
Current example requires php 7 (laravel 5.5)

**Comment by fsuuaas** [comment]
Windows doesn't support posix extension.

**Comment by pionl** [comment]
Ok then remove the phpunit/phpunit from the composer, it should help you.
