### ISSUE TITLE
Remove "minimum-stability" from composer config

### ISSUE THREAD

**Issue by nerg4l** [pionl/laravel-chunk-upload-example#12]
In the config file of composer the `"minimum-stability": "dev",` line causes the following issues:

- For some reason it makes composer to downloads the developer version all of the packagis. (Not just pionl/laravel-chunk-upload)
- Composer shows `no matching package found` for `ramsey/uuid`.

Once that line is removed everithing works as expected.

**Comment by pionl** [comment]
1. Thanks for the info, I've changed the minimum stability settings (latest commit)
2. `ramsey/uuid` is a dependency of laravel/framework.
