### ISSUE TITLE
Why my files grows when I upload?

### ISSUE THREAD

**Issue by fpcimmino** [pionl/laravel-chunk-upload-example#19]
When I upload one file of 93.1MB it become 2.6GB and is corrupted. Why?

**Comment by Venipa** [comment]
Chunks are getting merged after uploading

**Comment by pionl** [comment]
Hi, your Laravel version?

**Comment by fpcimmino** [comment]
It's laravel 6

**Comment by pionl** [comment]
This should be fine, what library you are using? Probably there is an issue that the library sends incorrect chunk index or file key. I would recommend to debug the data that is coming to find a solution.
