### ISSUE TITLE
only saves last chunk to upload folder

### ISSUE THREAD

**Issue by Chinese1904** [pionl/laravel-chunk-upload-example#2]
I just tried it with this fix out of curiosity and realized that only the last chunk gets moved to the upload folder. Later tonight I should have some free time to look at the code, in case I don't I might get back to it at a later time

**Comment by pionl** [comment]
It's required. First the uploads are uploaded in tmp folder for, in last chunk its builded in single file. Then it's your responsibility to move where you want it. The chunks folder is used for holding chunks and the uncompleted files are deleted :)

**Comment by pionl** [comment]
But you are right, sorry for that. The session in config is enabled and the jQuery upload is not sending cookies, will fix it. Thanks for the info !

**Comment by pionl** [comment]
The problem was that the session id is different under API. Thanks for the report.

**Comment by Chinese1904** [comment]
Sorry! I should have fixed it myself and send in the PR. Thanks for the work!

**Comment by pionl** [comment]
Don't be sorry my mistake ;) thankful for the report. Let me know if u need anything. Have a good day
