### ISSUE TITLE
suggestion: use storeAs() rather than move()

### ISSUE THREAD

**Issue by drjdr** [pionl/laravel-chunk-upload-example#21]
https://github.com/pionl/laravel-chunk-upload-example/blob/10259a2db9790dd0cbcefb9e66efca8895082f9a/example/src/Http/Controllers/UploadController.php#L105

since Illuminate\Http\UploadedFile is a dependency. 
On some linux machines move() throws an exception when the folder structure is not present. 
storeAs() has a factory to create this dir structure.

**Comment by pionl** [comment]
Nice suggestion -- it seems it was added in 5.3 :)

I will update the demo and run some tests, then I'll update the WIKI :)
