### ISSUE TITLE
Remove merged chunk file

### ISSUE THREAD

**Issue by ltrtuan** [pionl/laravel-chunk-upload-example#23]
Hi
I have a merged chunk file : NAMEVIDEO-oKqxtMjDY6c3Q63PrHzQjvzBmWKhSZPjflAjk4nn.part in storage/app/chunks folder.
I want to remove it after upload on Cloud server.
How can i do that. Thanks so much

**Comment by pionl** [comment]
When you merge the files you will get uploaded file that you can send to S3. Then you can delete it 👍
