### ISSUE TITLE
Add sample to upload in amazon s3 with dropzone js

### ISSUE THREAD

**Issue by Psalms23** [pionl/laravel-chunk-upload-example#5]
Hello, can you add an example on how to do this chunking with dropzone and upload it on s3. thank you so much

**Comment by pionl** [comment]
Hi, 

it same as "moving" the final file in local storage. Copied from https://itsolutionstuff.com/post/laravel-5-amazon-s3-file-upload-tutorial-part-2example.html

If the files are large, I would recommend to move the file locally and add a Queue job which will upload it to amazon.

```php
       $fileName = $this->createFilename($file);
       Storage::disk('s3')->put($fileName, file_get_contents($file), 'public');
        
        return response()->json([
            'path' => Storage::disk('s3')->url($fileName),
            'name' => $fileName,
            'mime_type' => $mime
        ]);
```

**Comment by Psalms23** [comment]
thanks @pionl

**Comment by archish1989** [comment]
using this sample code i have successfully upload file to AWS but in chunk folder 'filename.part' file is getting deleted by it self how can i delete that file? how can i delete files from chunk folder?

**Comment by pionl** [comment]
@archish1989 In example we are using move method. You need to manually delete the file by using unlink on the file`unlink($file->getPathname())`

**Comment by pionl** [comment]
I would suggest to use streaming: `$disk->putFileAs('photos', $file, $fileName);`

Docs: https://laravel.com/docs/5.3/filesystem#storing-files

**Comment by pionl** [comment]
Here is Wiki for this topic: https://github.com/pionl/laravel-chunk-upload/wiki/saving-to-cloud
