### ISSUE TITLE
Incorrect example?

### ISSUE THREAD

**Issue by mmjjb** [pionl/laravel-chunk-upload-example#6]
How are all demo's supposed to work with chunking, if only 1 is setup to do chunking?
Since:
-Dropzone
-Resumable

Only link to the original files, without any aditional configuration for chunking, so how is this "chunking" example going to do chunking, without any configuration?

Or am I missing something?

**Comment by pionl** [comment]
Hi @mmjjb,

unfortunatelly I do not understand your question. All the code uses basic setup for chunk upload. This repository shows real setup for given providers. When I have a time I would like to improve the documentation.

All JS can be found in `resources/assets/js`.

For dropzone: https://github.com/pionl/laravel-chunk-upload-example/blob/master/resources/assets/js/dropzone.js

For resumable: https://github.com/pionl/laravel-chunk-upload-example/blob/master/resources/assets/js/resumable.js

**Comment by mmjjb** [comment]
@pionl Thanks for clearing it up, I missed those files yesterday, since the vendor js files are loaded trough the blade and the other js files are loaded trough the route.

Why was chosen to load some trough the route and not just all in the blade?

**Comment by pionl** [comment]
I've updated the main repo with direct links the code - should be more clear now. Thanks for the feedback.

I do not like to load all the vendors in main bundle. I wanted to make the main bundle small as possible. Maybe a little overkill for an example 👻 Few days ago I've added also "show code" feature (which shows the files I've sent).
