### ISSUE TITLE
Call to undefined method Pion\Laravel\ChunkUpload\Handler\AbstractHandler::canUseSession()

### ISSUE THREAD

**Issue by asachanfbd** [pionl/laravel-chunk-upload-example#8]
Getting this error.

**Comment by pionl** [comment]
Hi, I've updated the composer.lock. Try this
```
git pull && composer install
```

**Comment by asachanfbd** [comment]
Thanks for quick reply. I already got it working by commenting out the code at App\Http\Controllers\DependencyUploadController.php #44 ['useSession' => AbstractHandler::canUseSession()] - Could not find any use of this in my implementation.

**Comment by pionl** [comment]
There was a problem with composer.lock, it had old version of the package.
