### ISSUE TITLE
The request is missing a file

### ISSUE THREAD

**Issue by archish1989** [pionl/laravel-chunk-upload-example#9]
I am using dropzone to upload file to AWS, and i am having this 'The request is missing a file.'  error.

` $aws=Storage::disk('s3');

            $receiver = new FileReceiver("media", $request, HandlerFactory::classFromRequest($request));
            if ($receiver->isUploaded() ) {
                // receive the file
                $save = $receiver->receive();
                // check if the upload has finished (in chunk mode it will send smaller files)
                if ($save->isFinished()  === true) {
                    // save the file and return any response you need
                    return $aws->put('test.mp3',$save->getFile(),'public');
                } else {
                    // we are in chunk mode, lets send the current progress
                    /** @var AbstractHandler $handler */
                    $handler = $save->handler();
                    return response()->json([
                        "done" => $handler->getPercentageDone(),
                    ]);
                }
            } else {
                throw new UploadMissingFileException();
            }`

and this is my dropzone code, here i am using angular 4

`            
              this.dropzoneConfig ={ 
			url : environment.apiurl+'/project/driveupload/?section=1&projectid='+this.projectId,
			acceptedFiles:"audio/*",
			autoReset:1,
			chunking: true,
			paramName: 'media',
			chunkSize:4000000
		};
`

why i am getting this error? what is i am doing wrong?

**Comment by pionl** [comment]
Hi @archish1989 , can you add dd($request) and copy the contents to this issue? Thanks

**Comment by archish1989** [comment]
I have solved this issue there was white space in parameter name, sorry to disturb you. can you help to verify that my php code is correct and it will upload files to AWS server?
your can save my day thank you. :)

**Comment by pionl** [comment]
Seems Ok to me, depends on your settings in config :)
